name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tolinsimpson'

      - name: Install dependencies
        working-directory: MinimaJS
        run: npm ci

      - name: Verify package
        working-directory: MinimaJS
        run: npm pack --dry-run

      - name: Build package
        working-directory: MinimaJS
        run: npm run build

      - name: Publish to GitHub Packages
        working-directory: MinimaJS
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
